---
title: "Aufgabe 1"
author: "windijon"
date: '2022-04-22'
output: beamer_presentation
---


Task 1: Import data

```{r}

library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data

Wildschwein_Daten <- read_csv(file = "wildschwein_BE.csv")
View(Wildschwein_Daten)

```


Task 2: Explore Data

```{r}

ggplot(Wildschwein_Daten, aes(Long, Lat, colour = TierID)) +
  geom_point()

```


Input I: Handling spatial data

```{r}

library(sf)

wildschwein_BE_sf <- st_as_sf(Wildschwein_Daten, 
                              coords = c("Long", "Lat"), 
                              crs = 4326)

Wildschwein_Daten

wildschwein_BE_sf

is.data.frame(wildschwein_BE_sf) # -> [1] TRUE

# subset rows
wildschwein_BE_sf[1:10,]
wildschwein_BE_sf[wildschwein_BE_sf$TierName == "Sabi",]

# subset colums
wildschwein_BE_sf[,2:3]

wildschwein_BE <- st_as_sf(Wildschwein_Daten, 
                          coords = c("Long", "Lat"), 
                          crs = 4326)

rm(wildschwein_BE_sf) 
# we can remove this sf object, since it just eats up our memory

```


Task 3: Project data from WGS84

```{r}

st_transform(x = wildschwein_BE, crs =  2056)

```


Input II: Calculate Convex Hull

```{r}

wildschwein_BE_grouped <- group_by(wildschwein_BE,TierID)
wildschwein_BE_grouped

wildschwein_BE_sample <- sample_n(wildschwein_BE_grouped, 2000)

wildschwein_BE_smry <- summarise(wildschwein_BE_sample)
wildschwein_BE_smry

mcp <- st_convex_hull(wildschwein_BE_smry)
mcp

```


Task 4: Ploting spatial objects

```{r}

plot(mcp)

ggplot(mcp, aes(colour = TierID)) +
  geom_sf() +
  coord_sf(datum =2056)

```


Input III: Importing raster data

```{r}

library(terra)
  
pk100_BE <- terra::rast("pk100_BE.tif")
pk100_BE

plot(pk100_BE)

plotRGB(pk100_BE)

```

